// Genre compatibility suggestions - which genres work well together
export const GENRE_COMPATIBILITY: Record<string, string[]> = {
  'fantasy': ['romance', 'mystery', 'horror', 'historical'],
  'science-fiction': ['thriller', 'mystery', 'horror', 'romance'],
  'romance': ['fantasy', 'mystery', 'historical', 'contemporary'],
  'mystery': ['thriller', 'historical', 'romance', 'horror'],
  'thriller': ['mystery', 'science-fiction', 'horror', 'romance'],
  'horror': ['mystery', 'thriller', 'fantasy', 'science-fiction'],
  'historical': ['romance', 'mystery', 'fantasy', 'literary'],
  'literary': ['contemporary', 'historical', 'romance'],
  'contemporary': ['romance', 'literary', 'mystery', 'thriller'],
  'western': ['romance', 'mystery', 'historical'],
  'romantasy': ['cozy-fantasy', 'fantasy'],
  'cozy-fantasy': ['romantasy', 'mystery'],
  'grimdark': ['fantasy', 'science-fiction'],
  'litrpg': ['fantasy', 'science-fiction'],
  'afrofuturism': ['science-fiction', 'fantasy'],
  'climate-fiction': ['science-fiction', 'thriller'],
  'solarpunk': ['science-fiction', 'romance'],
  'steampunk': ['mystery', 'romance', 'fantasy'],
  'new-weird': ['horror', 'fantasy', 'science-fiction'],
  'paranormal': ['romance', 'mystery', 'thriller'],
  'wuxia': ['fantasy', 'romance'],
  'legal-drama': ['thriller', 'romance', 'mystery'],
  'medical-drama': ['romance', 'thriller', 'mystery'],
  'sports-fiction': ['romance', 'contemporary'],
};
