// Popular genre combination recipes - pre-defined combinations that work well
export interface GenreRecipe {
  id: string;
  name: string;
  description: string;
  genres: string[];
  subgenres: string[];
  modifiers: string[];
  tones: string[];
  themes: string[];
  icon: string;
  popularity: 'hot' | 'popular' | 'niche';
}

export const GENRE_RECIPES: GenreRecipe[] = [
  {
    id: 'romantasy-classic',
    name: 'Romantasy',
    description: 'Fantasy romance with magical courts and forbidden love',
    genres: ['romantasy'],
    subgenres: ['Fae Romance'],
    modifiers: ['romantic'],
    tones: ['Romantic and Passionate', 'Epic and Grand'],
    themes: ['Forbidden Love', 'Power and Corruption'],
    icon: '💕✨',
    popularity: 'hot',
  },
  {
    id: 'cozy-mystery',
    name: 'Cozy Fantasy Mystery',
    description: 'Low-stakes magical mysteries in charming settings',
    genres: ['cozy-fantasy', 'mystery'],
    subgenres: ['Cozy Mystery Fantasy', 'Cozy Mystery'],
    modifiers: [],
    tones: ['Light and Humorous', 'Mysterious and Suspenseful'],
    themes: ['Secrets and Lies', 'Family and Loyalty'],
    icon: '🍵🔍',
    popularity: 'hot',
  },
  {
    id: 'space-opera-romance',
    name: 'Sci-Fi Romance',
    description: 'Love among the stars with epic space adventures',
    genres: ['science-fiction', 'romance'],
    subgenres: ['Space Opera', 'Slow Burn'],
    modifiers: ['romantic', 'adventure'],
    tones: ['Epic and Grand', 'Romantic and Passionate'],
    themes: ['Love and Sacrifice', 'Survival'],
    icon: '🚀💫',
    popularity: 'popular',
  },
  {
    id: 'dark-academia',
    name: 'Dark Academia Thriller',
    description: 'Sinister secrets at prestigious institutions',
    genres: ['thriller', 'mystery'],
    subgenres: ['Psychological Thriller', 'Whodunit'],
    modifiers: ['dark', 'psychological'],
    tones: ['Dark and Gritty', 'Mysterious and Suspenseful'],
    themes: ['Secrets and Lies', 'Ambition and Hubris'],
    icon: '📚🖤',
    popularity: 'popular',
  },
  {
    id: 'epic-grimdark',
    name: 'Epic Grimdark Fantasy',
    description: 'Brutal, morally grey epic fantasy with political intrigue',
    genres: ['grimdark', 'fantasy'],
    subgenres: ['Grimdark Fantasy', 'Epic Fantasy'],
    modifiers: ['political', 'military', 'dark'],
    tones: ['Dark and Gritty', 'Epic and Grand'],
    themes: ['Power and Corruption', 'Betrayal and Trust'],
    icon: '⚔️🩸',
    popularity: 'popular',
  },
  {
    id: 'litrpg-cultivation',
    name: 'Progression Fantasy',
    description: 'Power growth, levelling systems, and cultivation',
    genres: ['litrpg', 'fantasy'],
    subgenres: ['Progression Fantasy', 'Cultivation'],
    modifiers: ['action', 'adventure'],
    tones: ['Epic and Grand', 'Tense and Fast-Paced'],
    themes: ['Identity and Self-Discovery', 'Survival'],
    icon: '⚔️📈',
    popularity: 'popular',
  },
  {
    id: 'historical-romance',
    name: 'Historical Romance',
    description: 'Sweeping love stories set in bygone eras',
    genres: ['historical', 'romance'],
    subgenres: ['Victorian Era', 'Historical Romance'],
    modifiers: ['romantic'],
    tones: ['Romantic and Passionate', 'Epic and Grand'],
    themes: ['Forbidden Love', 'Class and Society'],
    icon: '👗💕',
    popularity: 'popular',
  },
  {
    id: 'supernatural-thriller',
    name: 'Supernatural Thriller',
    description: 'Fast-paced horror with relentless supernatural threats',
    genres: ['horror', 'thriller'],
    subgenres: ['Supernatural Horror', 'Action Thriller'],
    modifiers: ['action', 'dark'],
    tones: ['Tense and Fast-Paced', 'Dark and Gritty'],
    themes: ['Survival', 'Good vs Evil'],
    icon: '👻⚡',
    popularity: 'popular',
  },
  {
    id: 'solarpunk-hopeful',
    name: 'Hopepunk Solarpunk',
    description: 'Optimistic eco-futures with community and hope',
    genres: ['solarpunk'],
    subgenres: ['Eco-Utopia', 'Community-Focused SF'],
    modifiers: ['adventure'],
    tones: ['Hopeful and Uplifting', 'Whimsical and Fantastical'],
    themes: ['Nature vs Technology', 'Family and Loyalty'],
    icon: '🌱☀️',
    popularity: 'niche',
  },
  {
    id: 'afrofuturist-epic',
    name: 'Afrofuturist Epic',
    description: 'African diaspora perspectives in sweeping speculative narratives',
    genres: ['afrofuturism', 'fantasy'],
    subgenres: ['Afrofuturist Fantasy', 'African Mythology SF'],
    modifiers: ['epic'],
    tones: ['Epic and Grand', 'Hopeful and Uplifting'],
    themes: ['Legacy and Heritage', 'Identity and Self-Discovery'],
    icon: '🌍✨',
    popularity: 'niche',
  },
  {
    id: 'wuxia-romance',
    name: 'Martial Arts Romance',
    description: 'Love and honour among martial artists',
    genres: ['wuxia', 'romance'],
    subgenres: ['Wuxia Romance', 'Slow Burn'],
    modifiers: ['action', 'romantic'],
    tones: ['Epic and Grand', 'Romantic and Passionate'],
    themes: ['Love and Sacrifice', 'Forbidden Love'],
    icon: '🥋💕',
    popularity: 'niche',
  },
  {
    id: 'weird-horror',
    name: 'Cosmic Weird Horror',
    description: 'Reality-bending horror with cosmic dread',
    genres: ['new-weird', 'horror'],
    subgenres: ['Weird Horror', 'Cosmic Horror'],
    modifiers: ['psychological', 'dark'],
    tones: ['Dark and Gritty', 'Melancholic and Reflective'],
    themes: ['Fate vs Free Will', 'Isolation and Connection'],
    icon: '👁️🌀',
    popularity: 'niche',
  },
];
