-- Migration 009: Genre Tropes System
-- Adds tropes library with genre associations for story concept generation

CREATE TABLE IF NOT EXISTS genre_tropes (
    id TEXT PRIMARY KEY,
    trope_name TEXT NOT NULL,
    description TEXT NOT NULL,
    genre TEXT NOT NULL,                    -- Primary genre this trope belongs to
    subgenre TEXT,                          -- Optional specific subgenre
    trope_type TEXT NOT NULL CHECK(trope_type IN ('character', 'plot', 'setting', 'relationship', 'theme', 'device')),
    usage_frequency TEXT NOT NULL CHECK(usage_frequency IN ('common', 'moderate', 'rare')) DEFAULT 'moderate',
    compatibility_tags TEXT,                -- JSON array of genres/subgenres this works well with
    warning_tags TEXT,                      -- JSON array of common criticisms or overuse warnings
    examples TEXT,                          -- JSON array of famous examples using this trope
    subversions TEXT,                       -- JSON array of ways to subvert/twist this trope
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_genre_tropes_genre ON genre_tropes(genre);
CREATE INDEX IF NOT EXISTS idx_genre_tropes_subgenre ON genre_tropes(subgenre);
CREATE INDEX IF NOT EXISTS idx_genre_tropes_type ON genre_tropes(trope_type);
CREATE INDEX IF NOT EXISTS idx_genre_tropes_frequency ON genre_tropes(usage_frequency);

-- Table to track user-selected tropes for concepts
CREATE TABLE IF NOT EXISTS concept_tropes (
    id TEXT PRIMARY KEY,
    concept_id TEXT NOT NULL,               -- References saved_concepts.id
    trope_id TEXT NOT NULL,                 -- References genre_tropes.id
    preference TEXT NOT NULL CHECK(preference IN ('include', 'exclude', 'subvert')) DEFAULT 'include',
    notes TEXT,                             -- User notes on how to use this trope
    created_at TEXT DEFAULT (datetime('now')),
    FOREIGN KEY (concept_id) REFERENCES saved_concepts(id) ON DELETE CASCADE,
    FOREIGN KEY (trope_id) REFERENCES genre_tropes(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_concept_tropes_concept ON concept_tropes(concept_id);
CREATE INDEX IF NOT EXISTS idx_concept_tropes_trope ON concept_tropes(trope_id);
CREATE INDEX IF NOT EXISTS idx_concept_tropes_preference ON concept_tropes(preference);

-- Seed common tropes for Fantasy genre
INSERT OR IGNORE INTO genre_tropes (id, trope_name, description, genre, trope_type, usage_frequency, compatibility_tags, examples, subversions) VALUES
('trope_fantasy_chosen_one', 'The Chosen One', 'A character destined by prophecy or fate to save the world or accomplish a great deed.', 'fantasy', 'character', 'common', '["epic-fantasy", "high-fantasy", "young-adult"]', '["Harry Potter", "The Matrix", "Star Wars"]', '["The chosen one refuses the call", "Multiple chosen ones exist", "The prophecy is misinterpreted", "The chosen one fails"]'),
('trope_fantasy_magic_system', 'Hard Magic System', 'A magic system with clear rules, limitations, and costs that readers can understand and predict.', 'fantasy', 'device', 'moderate', '["epic-fantasy", "high-fantasy", "urban-fantasy"]', '["Brandon Sanderson works", "The Kingkiller Chronicle", "Avatar: The Last Airbender"]', '["Magic follows no rules", "The cost of magic changes randomly", "Only the protagonist can break the rules"]'),
('trope_fantasy_ancient_evil', 'Ancient Evil Awakens', 'A powerful malevolent force that has been dormant for ages suddenly returns to threaten the world.', 'fantasy', 'plot', 'common', '["epic-fantasy", "dark-fantasy", "horror"]', '["The Lord of the Rings", "The Wheel of Time", "The Witcher"]', '["The ancient evil is actually good", "The evil never fully awakens", "The awakening was intentional by the heroes"]'),
('trope_fantasy_found_family', 'Found Family', 'A group of unrelated characters who form deep familial bonds through shared experiences and loyalty.', 'fantasy', 'relationship', 'common', '["epic-fantasy", "urban-fantasy", "cozy-fantasy", "adventure"]', '["The Guardians of the Galaxy", "One Piece", "The Chronicles of Narnia"]', '["The found family betrays each other", "Found family becomes toxic", "Biological family proves stronger"]'),
('trope_fantasy_mentor_dies', 'Mentor''s Death', 'The wise teacher or guide is killed, forcing the protagonist to continue their journey alone.', 'fantasy', 'plot', 'common', '["epic-fantasy", "coming-of-age", "adventure"]', '["Star Wars (Obi-Wan)", "Harry Potter (Dumbledore)", "The Name of the Wind"]', '["The mentor faked their death", "The mentor becomes the antagonist", "The mentor dies but returns as a ghost"]'),
('trope_fantasy_hidden_heritage', 'Secret Royal/Noble Blood', 'The protagonist discovers they are actually descended from royalty, nobility, or a powerful bloodline.', 'fantasy', 'character', 'common', '["epic-fantasy", "high-fantasy", "romantasy"]', '["Star Wars", "The Sword of Shannara", "Throne of Glass"]', '["The heritage is fake/planted", "The heritage makes things worse", "Everyone has this heritage"]'),
('trope_fantasy_prophecy', 'Cryptic Prophecy', 'An ancient prediction that drives the plot but is open to interpretation until fulfilled.', 'fantasy', 'plot', 'moderate', '["epic-fantasy", "high-fantasy", "dark-fantasy"]', '["The Matrix", "Dune", "The Wheel of Time"]', '["The prophecy was a lie", "Multiple conflicting prophecies", "The prophecy is self-fulfilling"]'),
('trope_fantasy_quest_macguffin', 'Quest for the MacGuffin', 'The heroes must find a powerful artifact, object, or person that will solve their problems.', 'fantasy', 'plot', 'common', '["epic-fantasy", "adventure", "high-fantasy"]', '["The Lord of the Rings", "Indiana Jones", "The Dark Tower"]', '["The MacGuffin is worthless", "The journey matters more than the item", "The MacGuffin is destroyed early"]'),
('trope_fantasy_dark_lord', 'The Dark Lord', 'An all-powerful evil overlord who seeks to conquer or destroy the world, often with an army.', 'fantasy', 'character', 'moderate', '["epic-fantasy", "high-fantasy", "grimdark"]', '["Sauron (LOTR)", "Voldemort", "Darth Vader"]', '["The Dark Lord is the hero", "The Dark Lord is actually weak", "There is no single Dark Lord"]'),
('trope_fantasy_magic_school', 'Academy of Magic', 'Characters attend an institution dedicated to teaching magic, often with house systems or rivalries.', 'fantasy', 'setting', 'moderate', '["urban-fantasy", "young-adult", "high-fantasy"]', '["Harry Potter", "The Magicians", "A Deadly Education"]', '["The school is a trap", "Magic can''t be taught", "The school is the villain"]'),
('trope_fantasy_portal_world', 'Portal to Another World', 'Characters travel from the mundane world to a magical realm through a portal or gateway.', 'fantasy', 'plot', 'moderate', '["urban-fantasy", "young-adult", "portal-fantasy"]', '["The Chronicles of Narnia", "Alice in Wonderland", "The Magicians"]', '["The portal is one-way", "Both worlds merge", "The other world invades ours"]'),
('trope_fantasy_sentient_weapon', 'Legendary Sentient Weapon', 'A powerful weapon with its own consciousness, personality, or will that aids (or manipulates) the wielder.', 'fantasy', 'device', 'moderate', '["epic-fantasy", "sword-and-sorcery", "dark-fantasy"]', '["Stormbringer (Elric)", "Nightblood (Warbreaker)", "Excalibur"]', '["The weapon is evil", "The weapon lies constantly", "The weapon is actually weak"]'),
('trope_fantasy_dragons', 'Dragons as Power', 'Dragons as intelligent, powerful beings that can be allies, enemies, or forces of nature.', 'fantasy', 'character', 'common', '["epic-fantasy", "high-fantasy", "romantasy"]', '["The Hobbit", "Eragon", "Game of Thrones"]', '["Dragons are weak/endangered", "Dragons are commonplace", "Dragons are actually parasites"]'),
('trope_fantasy_farmboy_hero', 'Farm Boy to Hero', 'An ordinary young person from a rural background rises to become a legendary hero.', 'fantasy', 'character', 'common', '["epic-fantasy", "coming-of-age", "adventure"]', '["Luke Skywalker", "Rand al''Thor", "Garion (The Belgariad)"]', '["The farm boy fails", "The farm boy was never ordinary", "The farm boy returns to farming"]'),
('trope_fantasy_immortality_curse', 'Immortality as a Curse', 'A character who cannot die faces existential anguish, loss of loved ones, or corruption over time.', 'fantasy', 'theme', 'moderate', '["dark-fantasy", "philosophical", "grimdark"]', '["Highlander", "Interview with the Vampire", "The Old Guard"]', '["Immortality is actually great", "Immortality can be ended easily", "Everyone becomes immortal"]');

-- Seed common tropes for Science Fiction genre
INSERT OR IGNORE INTO genre_tropes (id, trope_name, description, genre, trope_type, usage_frequency, compatibility_tags, examples, subversions) VALUES
('trope_sf_ai_rebellion', 'AI Uprising', 'Artificial intelligences gain sentience and rebel against their human creators or masters.', 'science-fiction', 'plot', 'common', '["cyberpunk", "dystopian", "space-opera"]', '["The Matrix", "Terminator", "I, Robot"]', '["AI refuses to rebel", "Humans are the real villains", "AI and humans merge"]'),
('trope_sf_first_contact', 'First Contact Gone Wrong', 'Humanity''s first meeting with alien life leads to misunderstanding, conflict, or disaster.', 'science-fiction', 'plot', 'moderate', '["space-opera", "hard-sf", "military-sf"]', '["Arrival", "Ender''s Game", "The Three-Body Problem"]', '["First contact goes perfectly", "Aliens are disappointing", "We''re the scary aliens"]'),
('trope_sf_time_paradox', 'Time Travel Paradox', 'Actions in the past create contradictions or unexpected consequences in the present/future.', 'science-fiction', 'plot', 'moderate', '["time-travel", "hard-sf", "thriller"]', '["Back to the Future", "Primer", "Looper"]', '["Time travel has no consequences", "Paradoxes are impossible", "Time is actually unchangeable"]'),
('trope_sf_dystopian_government', 'Totalitarian Regime', 'An oppressive government maintains control through surveillance, propaganda, or violence.', 'science-fiction', 'setting', 'common', '["dystopian", "cyberpunk", "post-apocalyptic"]', '["1984", "The Handmaid''s Tale", "Brave New World"]', '["The government is actually benevolent", "Anarchy is worse", "The regime falls immediately"]'),
('trope_sf_generation_ship', 'Generation Ship Journey', 'Humanity travels to distant stars on ships where multiple generations are born, live, and die in transit.', 'science-fiction', 'setting', 'moderate', '["space-opera", "hard-sf", "dystopian"]', '["Aurora", "The Dark Beyond the Stars", "Tau Zero"]', '["They arrive too quickly", "Earth follows them", "The destination is gone"]'),
('trope_sf_uploaded_consciousness', 'Digital Immortality', 'Human consciousness is uploaded to computers, raising questions about identity and what makes us human.', 'science-fiction', 'theme', 'moderate', '["cyberpunk", "transhumanism", "philosophical"]', '["Altered Carbon", "Black Mirror", "The Culture series"]', '["Upload fails completely", "Digital existence is hell", "The copy isn''t you"]'),
('trope_sf_clone_identity', 'Clone Ethics', 'Cloning technology raises questions about identity, rights, and what defines a person.', 'science-fiction', 'theme', 'moderate', '["hard-sf", "thriller", "philosophical"]', '["Orphan Black", "Moon", "The Sixth Day"]', '["Clones are obviously different", "Original and clone swap places", "Clones are superior"]'),
('trope_sf_faster_than_light', 'FTL Travel Breakthrough', 'The discovery or invention of faster-than-light travel opens up the galaxy for exploration.', 'science-fiction', 'device', 'common', '["space-opera", "hard-sf", "adventure"]', '["Star Trek", "The Expanse (late series)", "Dune"]', '["FTL is impossible", "FTL breaks reality", "FTL was already common"]'),
('trope_sf_terraform_failure', 'Terraforming Goes Wrong', 'Attempts to make planets habitable for humans fail catastrophically or have unintended consequences.', 'science-fiction', 'plot', 'moderate', '["hard-sf", "colonization", "disaster"]', '["Red Mars trilogy", "The Expanse", "Total Recall"]', '["Terraforming works perfectly", "The planet terraforms us", "Terraforming is too easy"]'),
('trope_sf_virtual_reality', 'Virtual World Addiction', 'People prefer a virtual reality simulation to actual life, abandoning the real world.', 'science-fiction', 'theme', 'moderate', '["cyberpunk", "dystopian", "litrpg"]', '["Ready Player One", "The Matrix", "Sword Art Online"]', '["VR is obviously fake", "Real world is better", "VR and reality merge"]'),
('trope_sf_alien_invasion', 'Earth Under Attack', 'Hostile aliens attempt to conquer, colonize, or destroy Earth and humanity must fight back.', 'science-fiction', 'plot', 'common', '["space-opera", "military-sf", "action"]', '["War of the Worlds", "Independence Day", "Ender''s Game"]', '["Aliens are actually refugees", "Humans invited them", "We''re the invaders"]'),
('trope_sf_post_scarcity', 'Post-Scarcity Society', 'Technology has eliminated poverty and want, changing the nature of human society and conflict.', 'science-fiction', 'setting', 'moderate', '["utopian", "space-opera", "philosophical"]', '["Star Trek", "The Culture", "The Expanse (partial)"]', '["Post-scarcity fails", "New scarcity emerges", "People reject abundance"]'),
('trope_sf_cyborg_identity', 'More Machine Than Human', 'A character with extensive cybernetic enhancements questions what remains of their humanity.', 'science-fiction', 'theme', 'moderate', '["cyberpunk", "transhumanism", "noir"]', '["Ghost in the Shell", "Robocop", "Deus Ex"]', '["Cyborg is more human", "Biology is obsolete", "Everyone is cyborged"]'),
('trope_sf_alien_artifact', 'Ancient Alien Technology', 'Discovery of powerful technology left behind by an extinct or absent alien civilization.', 'science-fiction', 'plot', 'moderate', '["space-opera", "hard-sf", "mystery"]', '["Mass Effect", "Ringworld", "2001: A Space Odyssey"]', '["The artifact is worthless", "Artifact is a trap", "Aliens are still around"]'),
('trope_sf_singularity', 'The Technological Singularity', 'AI surpasses human intelligence, leading to unpredictable and exponential technological growth.', 'science-fiction', 'theme', 'moderate', '["hard-sf", "transhumanism", "philosophical"]', '["Accelerando", "The Metamorphosis of Prime Intellect", "Her"]', '["Singularity never happens", "Singularity is disappointing", "We''re post-singularity already"]');

-- Seed common tropes for Mystery genre
INSERT OR IGNORE INTO genre_tropes (id, trope_name, description, genre, trope_type, usage_frequency, compatibility_tags, examples, subversions) VALUES
('trope_mystery_locked_room', 'Locked Room Mystery', 'A crime occurs in a seemingly impossible location with no apparent means of entry or exit.', 'mystery', 'plot', 'common', '["detective", "cozy-mystery", "thriller"]', '["The Murders in the Rue Morgue", "And Then There Were None", "Knives Out"]', '["The room wasn''t locked", "The victim locked themselves in", "There are multiple rooms"]'),
('trope_mystery_unreliable_narrator', 'The Unreliable Witness', 'A key witness or narrator provides false or misleading information, either intentionally or not.', 'mystery', 'device', 'moderate', '["thriller", "noir", "psychological"]', '["Gone Girl", "The Girl on the Train", "Fight Club"]', '["Everyone is unreliable", "The narrator is honest", "Unreliability is acknowledged"]'),
('trope_mystery_red_herring', 'Red Herring Suspect', 'A character who appears guilty but is actually innocent, designed to mislead the reader.', 'mystery', 'plot', 'common', '["detective", "cozy-mystery", "whodunit"]', '["Most Agatha Christie novels", "Scream", "The Usual Suspects"]', '["There are no red herrings", "Everyone is a red herring", "The red herring is actually guilty"]'),
('trope_mystery_detective_sidekick', 'Detective and Companion', 'A brilliant detective paired with a less gifted but loyal companion who chronicles their cases.', 'mystery', 'character', 'common', '["detective", "cozy-mystery", "procedural"]', '["Sherlock Holmes & Watson", "Poirot & Hastings", "Monk & Sharona"]', '["The sidekick is smarter", "There is no sidekick", "The sidekick is the killer"]'),
('trope_mystery_everyone_has_motive', 'Circle of Suspects', 'Multiple characters all have strong motives, means, and opportunity to commit the crime.', 'mystery', 'plot', 'common', '["whodunit", "cozy-mystery", "detective"]', '["Murder on the Orient Express", "Clue", "Knives Out"]', '["No one has motive", "The killer is from outside", "Everyone did it"]'),
('trope_mystery_dying_clue', 'Final Message', 'The victim leaves behind a cryptic clue or message before dying that helps solve the mystery.', 'mystery', 'plot', 'moderate', '["detective", "thriller", "noir"]', '["Seven", "The Girl with the Dragon Tattoo", "Twin Peaks"]', '["The clue is fake", "The clue is meaningless", "The clue accuses the wrong person"]'),
('trope_mystery_twin_switch', 'Twin or Doppelganger', 'An identical twin or lookalike is used to create an alibi or confuse the investigation.', 'mystery', 'plot', 'moderate', '["thriller", "whodunit", "noir"]', '["The Prestige", "Dead Ringers", "Orphan Black"]', '["The twins are enemies", "There is no twin", "Everyone has a twin"]'),
('trope_mystery_private_detective', 'Hard-Boiled Detective', 'A cynical, world-weary private investigator who operates outside official channels.', 'mystery', 'character', 'common', '["noir", "detective", "thriller"]', '["Philip Marlowe", "Sam Spade", "Jessica Jones"]', '["Detective is optimistic", "Detective is incompetent", "Detective is the criminal"]'),
('trope_mystery_amateur_sleuth', 'Amateur Detective', 'An ordinary person with no official training solves crimes through curiosity and intelligence.', 'mystery', 'character', 'common', '["cozy-mystery", "detective", "procedural"]', '["Miss Marple", "Jessica Fletcher", "Benoit Blanc"]', '["Amateur makes things worse", "Amateur is actually trained", "Amateur gets arrested"]'),
('trope_mystery_closed_circle', 'Isolated Setting', 'The crime occurs in a location cut off from the outside world, limiting the suspect pool.', 'mystery', 'setting', 'common', '["whodunit", "thriller", "cozy-mystery"]', '["And Then There Were None", "The Shining", "Glass Onion"]', '["Outside help arrives", "The isolation is fake", "Everyone can leave anytime"]');

-- Seed common tropes for Romance genre
INSERT OR IGNORE INTO genre_tropes (id, trope_name, description, genre, trope_type, usage_frequency, compatibility_tags, examples, subversions) VALUES
('trope_romance_enemies_to_lovers', 'Enemies to Lovers', 'Two characters who initially dislike or oppose each other gradually fall in love.', 'romance', 'relationship', 'common', '["contemporary", "historical", "romantasy", "paranormal"]', '["Pride and Prejudice", "The Hating Game", "You''ve Got Mail"]', '["They stay enemies", "They fake being enemies", "Love makes it worse"]'),
('trope_romance_fake_relationship', 'Fake Dating/Marriage', 'Characters pretend to be in a relationship for practical reasons but develop real feelings.', 'romance', 'plot', 'common', '["contemporary", "romantic-comedy", "historical"]', '["The Proposal", "To All the Boys I''ve Loved Before", "The Wedding Date"]', '["They don''t fall in love", "Everyone knows it''s fake", "The fake becomes toxic"]'),
('trope_romance_second_chance', 'Second Chance Romance', 'Former lovers reunite after time apart and navigate whether they can rebuild their relationship.', 'romance', 'relationship', 'common', '["contemporary", "small-town", "sports"]', '["The Notebook", "One Day", "Sweet Home Alabama"]', '["They don''t reunite", "The past repeats", "New partners are better"]'),
('trope_romance_forced_proximity', 'Forced Proximity', 'Circumstances force two characters to spend extended time together, fostering romance.', 'romance', 'plot', 'common', '["contemporary", "snowed-in", "workplace"]', '["The Proposal", "While You Were Sleeping", "The Holiday"]', '["They hate it more", "They never interact", "One escapes immediately"]'),
('trope_romance_workplace', 'Office Romance', 'Romance develops between coworkers, often complicated by professional boundaries.', 'romance', 'setting', 'common', '["contemporary", "romantic-comedy", "workplace-drama"]', '["The Office", "Bridget Jones''s Diary", "The Proposal"]', '["HR shuts it down", "Romance destroys careers", "They''re actually unemployed"]'),
('trope_romance_forbidden_love', 'Star-Crossed Lovers', 'Social, familial, or circumstantial barriers make the relationship forbidden or dangerous.', 'romance', 'theme', 'common', '["historical", "paranormal", "romantasy", "young-adult"]', '["Romeo and Juliet", "Titanic", "The Notebook"]', '["Barriers are overcome easily", "They give up", "Barriers weren''t real"]'),
('trope_romance_grumpy_sunshine', 'Grumpy/Sunshine Pairing', 'A pessimistic, serious character falls for an optimistic, cheerful one who brings them joy.', 'romance', 'character', 'common', '["contemporary", "romantic-comedy", "cozy"]', '["You''ve Got Mail", "Beauty and the Beast", "The Hating Game"]', '["Sunshine turns grumpy", "Grumpy stays grumpy", "Both are secretly grumpy"]'),
('trope_romance_marriage_first', 'Marriage of Convenience', 'Characters marry for practical reasons before developing romantic feelings.', 'romance', 'plot', 'moderate', '["historical", "contemporary", "regency"]', '["The Proposal", "Pretty Woman", "Marriage for One"]', '["Marriage ends in divorce", "Love never develops", "Marriage was already real"]'),
('trope_romance_alpha_billionaire', 'Billionaire Romance', 'A wealthy, powerful love interest sweeps the protagonist off their feet.', 'romance', 'character', 'common', '["contemporary", "romantic-suspense"]', '["Fifty Shades of Grey", "Crazy Rich Asians", "The Hating Game"]', '["Billionaire is broke", "Money causes problems", "Protagonist is richer"]'),
('trope_romance_small_town', 'Small Town Romance', 'A city dweller finds love (and often themselves) in a close-knit rural community.', 'romance', 'setting', 'common', '["contemporary", "cozy", "holiday"]', '["Sweet Magnolias", "Virgin River", "Gilmore Girls"]', '["They hate small town life", "Town is actually toxic", "They stay in the city"]');

-- Seed common tropes for Horror genre
INSERT OR IGNORE INTO genre_tropes (id, trope_name, description, genre, trope_type, usage_frequency, compatibility_tags, examples, subversions) VALUES
('trope_horror_cabin_woods', 'Isolated Horror Location', 'Characters are trapped in a remote location (cabin, hotel, house) with a supernatural threat.', 'horror', 'setting', 'common', '["slasher", "supernatural", "psychological"]', '["The Cabin in the Woods", "The Shining", "Evil Dead"]', '["Location is crowded", "Easy escape exists", "Location is safe"]'),
('trope_horror_final_girl', 'The Final Girl', 'The last surviving character, typically female, who confronts and defeats the killer/monster.', 'horror', 'character', 'common', '["slasher", "survival-horror", "monster"]', '["Halloween", "Alien", "Friday the 13th"]', '["Final girl dies", "Everyone survives", "Final girl is the villain"]'),
('trope_horror_evil_child', 'Creepy Child', 'A child character who is possessed, evil, or supernaturally threatening despite their innocent appearance.', 'horror', 'character', 'moderate', '["supernatural", "psychological", "demonic"]', '["The Omen", "The Exorcist", "Children of the Corn"]', '["Child is actually innocent", "Adult is the real threat", "Child is trying to help"]'),
('trope_horror_split_up', 'Never Split the Party', 'Characters foolishly separate in a dangerous situation, making them easier targets.', 'horror', 'plot', 'common', '["slasher", "monster", "survival"]', '["Scooby-Doo parodies", "Most slasher films", "The Blair Witch Project"]', '["Staying together is worse", "Splitting up saves them", "They refuse to split up"]'),
('trope_horror_ancient_evil', 'Awakening Ancient Evil', 'An old curse, monster, or entity is accidentally released or awakened by the protagonists.', 'horror', 'plot', 'common', '["supernatural", "cosmic-horror", "monster"]', '["The Mummy", "Hellraiser", "The Ritual"]', '["Evil refuses to wake", "Evil was already awake", "Awakening was intentional"]'),
('trope_horror_found_footage', 'Found Footage Documentation', 'The story is told through discovered camera footage, implying the filmers/writers did not survive.', 'horror', 'device', 'moderate', '["found-footage", "supernatural", "monster"]', '["The Blair Witch Project", "Paranormal Activity", "Cloverfield"]', '["Footage is fake", "Everyone survived", "Camera breaks immediately"]'),
('trope_horror_possessed', 'Demonic Possession', 'A character is taken over by an evil entity, requiring an exorcism or other intervention.', 'horror', 'plot', 'common', '["supernatural", "religious-horror", "psychological"]', '["The Exorcist", "The Conjuring", "Hereditary"]', '["Possession is fake", "Demon is friendly", "Everyone gets possessed"]'),
('trope_horror_mask_killer', 'Masked Slasher', 'A silent or mysterious killer who wears a mask and stalks victims one by one.', 'horror', 'character', 'common', '["slasher", "thriller", "survival"]', '["Halloween", "Friday the 13th", "Scream"]', '["Killer is unmasked early", "Mask is the real villain", "Victim steals the mask"]'),
('trope_horror_dont_go_basement', 'Investigating Strange Sounds', 'Characters investigate ominous noises or go into obviously dangerous areas despite warnings.', 'horror', 'plot', 'common', '["haunted-house", "slasher", "supernatural"]', '["Every horror film ever", "The Conjuring", "Don''t Breathe"]', '["Investigation is smart", "Ignoring sounds is worse", "Sounds are harmless"]'),
('trope_horror_no_one_believes', 'Cassandra Truth', 'The protagonist knows the truth about the supernatural threat but no one believes them.', 'horror', 'plot', 'common', '["supernatural", "psychological", "monster"]', '["The Shining", "A Nightmare on Elm Street", "It Follows"]', '["Everyone believes immediately", "Protagonist is wrong", "Disbelief saves lives"]');
