// Subgenre definitions organised by parent genre
// Extracted from GenrePreferenceForm for reusability

export interface SubgenreOption {
  value: string;
  description: string;
}

export const SUBGENRES: Record<string, SubgenreOption[]> = {
  afrofuturism: [
    { value: 'Afrofuturist SF', description: 'African diaspora perspectives on future technology and society' },
    { value: 'Afrofuturist Fantasy', description: 'African mythology and magic in speculative settings' },
    { value: 'Afro-Cyberpunk', description: 'High-tech, low-life through an African lens' },
    { value: 'African Mythology SF', description: 'Traditional African gods and spirits in science fiction' },
    { value: 'Black Space Opera', description: 'Epic galactic adventures centering Black characters' },
    { value: 'Afrofuturist Horror', description: 'Horror drawing on African folklore and diaspora fears' },
  ],
  'climate-fiction': [
    { value: 'Near Future Climate', description: 'Climate change impacts in the next 20-50 years' },
    { value: 'Climate Disaster', description: 'Catastrophic weather events and their aftermath' },
    { value: 'Eco-Thriller', description: 'Environmental stakes with suspenseful pacing' },
    { value: 'Solarpunk Utopia', description: 'Optimistic sustainable futures achieved' },
    { value: 'Post-Climate Collapse', description: 'Survival after environmental catastrophe' },
    { value: 'Climate Mystery', description: 'Solving crimes or puzzles in a changed climate' },
  ],
  contemporary: [
    { value: 'Family Drama', description: 'Complex family relationships and generational dynamics' },
    { value: 'Coming of Age', description: 'Young protagonists navigating growth and identity' },
    { value: 'Social Issues', description: 'Stories addressing contemporary societal challenges' },
    { value: 'Workplace Drama', description: 'Office politics, career struggles, and professional life' },
    { value: 'Slice of Life', description: 'Everyday moments that reveal deeper truths' },
  ],
  'cozy-fantasy': [
    { value: 'Slice of Life Fantasy', description: 'Daily life in magical settings without major conflict' },
    { value: 'Cozy Mystery Fantasy', description: 'Low-stakes puzzles in warm, magical communities' },
    { value: 'Cozy Romance Fantasy', description: 'Sweet love stories in comfortable magical worlds' },
    { value: 'Low Stakes Adventure', description: 'Gentle quests without world-ending consequences' },
    { value: 'Found Family Fantasy', description: 'Building chosen families in magical settings' },
    { value: 'Cottage Core Fantasy', description: 'Rural, pastoral magic with simple pleasures' },
  ],
  fantasy: [
    { value: 'Epic Fantasy', description: 'World-spanning quests with multiple POVs and high stakes' },
    { value: 'Urban Fantasy', description: 'Magic hidden in modern cities and urban environments' },
    { value: 'Dark Fantasy', description: 'Grim settings where magic has terrible costs' },
    { value: 'High Fantasy', description: 'Secondary worlds with elaborate magic systems' },
    { value: 'Low Fantasy', description: 'Subtle magic in realistic or historical settings' },
    { value: 'Sword & Sorcery', description: 'Action-focused adventures with warriors and wizards' },
  ],
  grimdark: [
    { value: 'Grimdark Fantasy', description: 'Morally grey characters in brutal fantasy worlds' },
    { value: 'Grimdark Sci-Fi', description: 'Cynical, violent science fiction futures' },
    { value: 'Military Grimdark', description: 'The horrors of warfare without glorification' },
    { value: 'Cosmic Grimdark', description: 'Nihilistic horror at the scale of the universe' },
    { value: 'Historical Grimdark', description: 'Real history shown at its darkest' },
    { value: 'Post-Apocalyptic Grimdark', description: 'Humanity at its worst after collapse' },
  ],
  historical: [
    { value: 'Ancient History', description: 'Greece, Rome, Egypt, or other ancient civilisations' },
    { value: 'Medieval', description: 'Knights, castles, and feudal society' },
    { value: 'Victorian Era', description: '19th century manners, industry, and empire' },
    { value: 'World War Era', description: 'Stories set during WWI or WWII' },
    { value: '20th Century', description: 'Modern history from 1900-1999' },
    { value: 'Alternate History', description: 'What if key historical events went differently?' },
  ],
  horror: [
    { value: 'Supernatural Horror', description: 'Ghosts, demons, and things that go bump in the night' },
    { value: 'Psychological Horror', description: 'Terror from within the mind' },
    { value: 'Gothic Horror', description: 'Atmospheric dread in crumbling mansions and moors' },
    { value: 'Cosmic Horror', description: 'Incomprehensible entities and existential dread' },
    { value: 'Body Horror', description: 'Disturbing transformations of the human form' },
  ],
  'legal-drama': [
    { value: 'Courtroom Drama', description: 'Tension and revelation in the courtroom' },
    { value: 'Legal Thriller', description: 'High-stakes cases with dangerous consequences' },
    { value: 'Criminal Defense', description: 'Defending the accused against the system' },
    { value: 'Corporate Law', description: 'Big business, mergers, and white-collar crime' },
    { value: 'Legal Mystery', description: 'Solving crimes through legal investigation' },
    { value: 'Legal Romance', description: 'Love among lawyers and legal professionals' },
  ],
  literary: [
    { value: 'Contemporary Literary', description: 'Modern life explored with literary depth' },
    { value: 'Experimental', description: 'Breaking narrative conventions and forms' },
    { value: 'Philosophical', description: 'Ideas and big questions drive the narrative' },
    { value: 'Character-Driven', description: 'Deep character studies over plot' },
    { value: 'Magical Realism', description: 'Magic woven seamlessly into realistic settings' },
  ],
  litrpg: [
    { value: 'Dungeon Core', description: 'Protagonist becomes or manages a dungeon' },
    { value: 'GameLit', description: 'Game elements without full stat systems' },
    { value: 'Virtual Reality', description: 'Adventures inside VR game worlds' },
    { value: 'System Apocalypse', description: 'Game mechanics invade the real world' },
    { value: 'Progression Fantasy', description: 'Power growth and leveling as core focus' },
    { value: 'Cultivation', description: 'Eastern-style power cultivation and martial arts' },
  ],
  'medical-drama': [
    { value: 'Hospital Drama', description: 'Day-to-day challenges in medical settings' },
    { value: 'Medical Thriller', description: 'Life-or-death stakes and medical mysteries' },
    { value: 'Medical Mystery', description: 'Diagnosing unusual or mysterious conditions' },
    { value: 'Medical Romance', description: 'Love stories among healthcare workers' },
    { value: 'Emergency Medicine', description: 'High-pressure ER and trauma scenarios' },
    { value: 'Medical Horror', description: 'Body horror and medical nightmares' },
  ],
  mystery: [
    { value: 'Cozy Mystery', description: 'Amateur sleuths solving crimes in charming settings' },
    { value: 'Police Procedural', description: 'Realistic police investigation methods' },
    { value: 'Detective', description: 'Professional or private investigators at work' },
    { value: 'Noir', description: 'Dark, cynical mysteries with morally grey protagonists' },
    { value: 'Whodunit', description: 'Classic puzzle mysteries with clues for readers' },
    { value: 'Legal Mystery', description: 'Crimes solved through legal processes' },
  ],
  'new-weird': [
    { value: 'Urban Weird', description: 'Strange happenings in city environments' },
    { value: 'Weird Horror', description: 'Horror that defies classification' },
    { value: 'Weird Fantasy', description: 'Fantasy that breaks genre conventions' },
    { value: 'Slipstream', description: 'Genre-fluid narratives between realism and fantasy' },
    { value: 'Bizarro Fiction', description: 'Deliberately absurd and transgressive' },
    { value: 'Surreal Fiction', description: 'Dreamlike logic and impossible imagery' },
  ],
  paranormal: [
    { value: 'Paranormal Mystery', description: 'Solving crimes with supernatural elements' },
    { value: 'Paranormal Thriller', description: 'High-stakes supernatural suspense' },
    { value: 'Paranormal Investigation', description: 'Ghost hunters and supernatural researchers' },
    { value: 'Ghost Stories', description: 'Classic tales of haunting and spirits' },
    { value: 'Supernatural Drama', description: 'Character-focused supernatural narratives' },
    { value: 'Paranormal Action', description: 'Fast-paced supernatural combat' },
  ],
  romance: [
    { value: 'Contemporary Romance', description: 'Modern-day love stories and relationships' },
    { value: 'Historical Romance', description: 'Love across historical time periods' },
    { value: 'Paranormal Romance', description: 'Love with vampires, shifters, or other beings' },
    { value: 'Romantic Comedy', description: 'Lighthearted love stories with humour' },
    { value: 'Slow Burn', description: 'Gradually building romantic tension' },
  ],
  romantasy: [
    { value: 'Fae Romance', description: 'Love stories with faeries and magical courts' },
    { value: 'Witch Romance', description: 'Magic users finding love and power' },
    { value: 'Dragon Romance', description: 'Dragons as love interests or shifters' },
    { value: 'Vampire Romance', description: 'Immortal romance with bloodsucking twist' },
    { value: 'Magical Royalty Romance', description: 'Princes, princesses, and magical kingdoms' },
    { value: 'Court Intrigue Romance', description: 'Love amid political machinations' },
  ],
  'science-fiction': [
    { value: 'Space Opera', description: 'Epic adventures across galaxies and star systems' },
    { value: 'Cyberpunk', description: 'High tech, low life in neon-lit futures' },
    { value: 'Hard SF', description: 'Scientifically rigorous speculation' },
    { value: 'Dystopian', description: 'Oppressive future societies and resistance' },
    { value: 'Post-Apocalyptic', description: 'Survival after civilisation falls' },
    { value: 'First Contact', description: 'Humanity meeting alien intelligence' },
  ],
  solarpunk: [
    { value: 'Eco-Utopia', description: 'Thriving sustainable societies achieved' },
    { value: 'Green Tech SF', description: 'Environmental technology saving the world' },
    { value: 'Sustainable Future', description: 'Harmony between humanity and nature' },
    { value: 'Hopeful Climate Fiction', description: 'Optimistic takes on environmental challenges' },
    { value: 'Community-Focused SF', description: 'Collective action and community building' },
    { value: 'Biomimicry Fiction', description: 'Technology inspired by nature' },
  ],
  'sports-fiction': [
    { value: 'Sports Drama', description: 'Emotional journeys through athletic competition' },
    { value: 'Sports Romance', description: 'Love on and off the field' },
    { value: 'Underdog Sports', description: 'Against-the-odds athletic triumph' },
    { value: 'Professional Sports', description: 'Life in pro leagues and big-time athletics' },
    { value: 'College Sports', description: 'Competition and growth in collegiate athletics' },
    { value: 'Fantasy Sports', description: 'Fictional sports in imaginary worlds' },
  ],
  steampunk: [
    { value: 'Victorian Steampunk', description: 'Classic steam technology in Victorian settings' },
    { value: 'Dieselpunk', description: 'Art deco aesthetics and diesel technology' },
    { value: 'Clockpunk', description: 'Clockwork and mechanical wonders' },
    { value: 'Gaslamp Fantasy', description: 'Victorian fantasy with gas-lit atmosphere' },
    { value: 'Steampunk Romance', description: 'Love amid gears and goggles' },
    { value: 'Post-Apocalyptic Steampunk', description: 'Steam technology after modern collapse' },
  ],
  thriller: [
    { value: 'Psychological Thriller', description: 'Mind games and unreliable narrators' },
    { value: 'Action Thriller', description: 'Fast-paced physical danger and chases' },
    { value: 'Legal Thriller', description: 'Courtroom stakes and legal danger' },
    { value: 'Medical Thriller', description: 'Life-or-death medical situations' },
    { value: 'Spy Thriller', description: 'Espionage, tradecraft, and international intrigue' },
  ],
  western: [
    { value: 'Classic Western', description: 'Traditional frontier adventures and showdowns' },
    { value: 'Weird West', description: 'Supernatural elements in the Old West' },
    { value: 'Space Western', description: 'Frontier spirit on alien worlds' },
    { value: 'Contemporary Western', description: 'Modern-day stories in the American West' },
    { value: 'Western Romance', description: 'Love on the frontier' },
    { value: 'Revisionist Western', description: 'Challenging western tropes and perspectives' },
  ],
  wuxia: [
    { value: 'Classical Wuxia', description: 'Traditional Chinese martial arts adventure' },
    { value: 'Xianxia Cultivation', description: 'Cultivating immortality and spiritual power' },
    { value: 'Modern Wuxia', description: 'Martial arts in contemporary settings' },
    { value: 'Wuxia Romance', description: 'Love among martial artists' },
    { value: 'Historical Wuxia', description: 'Martial arts in specific Chinese dynasties' },
    { value: 'Mythological Wuxia', description: 'Blending wuxia with Chinese mythology' },
  ],
};
